### ISSUE TITLE
go-sharding

### ISSUE THREAD

**Issue by lulufeiacount** [endink/go-sharding#6]
哥们你这是全部重构了呀，基本上看不出来有gaea的影子

**Comment by endink** [comment]
额~ 没弄完，但是有空就弄弄，工程浩大，全部重构了，小米代码说实话，太乱了，粘贴了各种库的代码，要加点东西接口也没有，全部要改实现，我觉得 ShardingSphere 的路由配置值得借鉴，所以现实了一把，kingshard， mycat 那种运维都不知道怎么配，非常不直观

**Comment by lulufeiacount** [comment]
看了一下代码风格，确实很爽。

**Comment by lulufeiacount** [comment]
哥们在哪高就呢？想跟着哥们混。

**Comment by endink** [comment]
@lulufeiacount 自由职业啰
